In [1]:
import pandas as pd
import numpy as np
import warnings as wr #Ignores the warnings
wr.filterwarnings('ignore')

In [2]:

df = pd.read_csv('shoe.csv')

In [3]:

df.head()

size(cm) class(y)
0     9.500   Female
1    10.125     Male
2    10.410     Male
3     9.810   Female
4    11.050     Male

In [4]:
df.shape

(40, 2)

In [5]:

# Replace class labels with numeric values
df['class(y)'] = df['class(y)'].replace(['Female','Male'],[0,1])

In [6]:

df.head()

size(cm)  class(y)
0     9.500         0
1    10.125         1
2    10.410         1
3     9.810         0
4    11.050         1

In [7]:

# Separate features (x) and target variable (y)

x=df.drop('class(y)', axis=1)

In [8]:
y=df[['class(y)']]
     

In [9]:
from sklearn.linear_model import LogisticRegression
     

In [10]:
# Train the logistic regression model

reg = LogisticRegression()

In [11]:
reg.fit(x,y)

LogisticRegression()

In [12]:
reg.coef_

array([[2.62699981]])

In [13]:
reg.intercept_

array([-26.18198935])

In [14]:

reg.predict(x)

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [15]:

y.tail()

class(y)
35         0
36         0
37         1
38         0
39         1

In [16]:

reg.predict_proba(x)

array([[0.77302845, 0.22697155],
       [0.39738242, 0.60261758],
       [0.2377457 , 0.7622543 ],
       [0.6013567 , 0.3986433 ],
       [0.05486986, 0.94513014],
       [0.8951951 , 0.1048049 ],
       [0.79524583, 0.20475417],
       [0.17003227, 0.82996773],
       [0.66235827, 0.33764173],
       [0.69665958, 0.30334042],
       [0.59504263, 0.40495737],
       [0.23301782, 0.76698218],
       [0.35729164, 0.64270836],
       [0.07737361, 0.92262639],
       [0.17757582, 0.82242418],
       [0.11860381, 0.88139619],
       [0.46492055, 0.53507945],
       [0.52395197, 0.47604803],
       [0.29398481, 0.70601519],
       [0.16274575, 0.83725425],
       [0.38176611, 0.61823389],
       [0.83473184, 0.16526816],
       [0.88221669, 0.11778331],
       [0.1392146 , 0.8607854 ],
       [0.71305157, 0.28694843],
       [0.21476669, 0.78523331],
       [0.2994667 , 0.7005333 ],
       [0.09833362, 0.90166638],
       [0.2192301 , 0.7807699 ],
       [0.11860381, 0.88139619],
       [0.

In [17]:
# Test data
test_data = np.array([[0.8]])

# Predict the probabilities for the test data
predicted_probabilities = reg.predict_proba(test_data)

# Extract the predicted class label
predicted_label = reg.predict(test_data)

# Convert the predicted label to the corresponding gender
predicted_gender = "Male" if predicted_label[0] == 1 else "Female"

# Extract the probability for the predicted class label
predicted_probability = predicted_probabilities[0][predicted_label[0]]

# Print the predicted gender and probability
print(f"Predicted gender for test data 0.8: {predicted_gender}")
print(f"Probability for the predicted gender: {predicted_probability}")


Predicted gender for test data 0.8: Female
Probability for the predicted gender: 0.9999999999651646


In [18]:

# Extract the learned parameters
m = reg.coef_[0][0] #represents the coefficient of the feature (x) in the logistic regression model
c = reg.intercept_[0] #represents the intercept term

In [19]:
# Define sigmoid function
def sigmoid_function(x):
    return 1 / (1 + np.exp(-(m * x + c)))

#x is the feature value (e.g., shoe size).
#m is the coefficient of the feature.
#c is the intercept term.
     

In [20]:
# Test the sigmoid function
test_value = 0.8
sigmoid_result = sigmoid_function(test_value)

# Determine the predicted gender based on the sigmoid result
predicted_gender = "Male" if sigmoid_result >= 0.5 else "Female"

# Print the predicted gender and sigmoid result
print(f"Predicted gender for test data 0.8: {predicted_gender}")
print(f"Sigmoid result for test data 0.8: {sigmoid_result}")

Predicted gender for test data 0.8: Female
Sigmoid result for test data 0.8: 3.4835313028574484e-11


In [21]:
# Define the sigmoid function
def sigmoid_function(x, m, c):
    return 1 / (1 + np.exp(-(m * x + c)))

# Define the values of m, c, and x
m = 1.5
c = -2.0
x = 0.8

# Calculate the sigmoid result
sigmoid_result = sigmoid_function(x, m, c)

# Print the sigmoid result
print(f"Sigmoid result for {x}: {sigmoid_result}")

Sigmoid result for 0.8: 0.3100255188723876


In [22]:
import numpy as np

# Define sigmoid function
def sigmoid_function(x, m, c):
    exponential_term = np.exp(-(m * x + c))
    sigmoid_result = 1 / (1 + exponential_term)
    return sigmoid_result

# Example
test_value = 0.8
m = 0.5
c = -0.3
sigmoid_result = sigmoid_function(test_value, m, c)
print(f"Sigmoid result for {test_value}: {sigmoid_result}")

Sigmoid result for 0.8: 0.52497918747894
